baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = 'Textos'
theme = "PaperMod"
copyright = "© [Pablo Andrade](https://www.instagram.com/pablodeas/)"
DefaultContentLanguage = "pt"

[taxonomies]
    category = "categories"
    tag = "tags"

[languages.pt]
    languageName = "Português"
    weight = 1
    contentDir = "content/pt"

    [languages.pt.menu]
        [[languages.pt.menu.main]]
            name = "Poesia"
            url = "categories/poesia"
            weight = 10
        [[languages.pt.menu.main]]
            name = "Prosa"
            url = "categories/prosa"
            weight = 20
        [[languages.pt.menu.main]]
            name = "Conto"
            url = "categories/conto"
            weight = 30
        [[languages.pt.menu.main]]
            name = "Filtro por Data" # Página que mostra tudo organizado
            url = "archives"
            weight = 40

[params]
    env = "production"
    title = "Pablo A."
    description = "Escritos de Pablo"
    author = "Pablo"

    # googleAnalytics = "G-7W7PLMK08D"

    # Configurações visuais do PaperMod
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowTaxonomies = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true

    assets = { disableHLJS = false }
    
    # Página inicial (Profile Mode como o Yinyang, mas com menu)
    [params.homeInfoParams]
        Title = "Pablo Andrade"
        Content = "Textos Autorais."

    [[params.socialIcons]]
        name = "instagram"
        url = "https://www.instagram.com/pablodeas/"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/pablodeas"